### ISSUE TITLE
No installation instructions in README.md

### ISSUE THREAD

**Issue by PseudonymPatel** [Michael-Reeves-Discord-Community/Michael-Reeves-Community-Bot#9]
Yo this is ComputerButter (CEO of Swift). I thought I'd make issues rather than discord dms because y'all said you were sleeping and I could write more here.

So... There's no installation instructions in the readme, what packages do I need (requirements.txt), what version of python, basically enough stuff to have someone able to compile and use the code themselves.

**Comment by shrig1** [comment]
Yes, we are working on that at the moment
